name: guide_me
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  firebase_ui_auth: ^1.16.0
  cloud_firestore: ^5.5.1
  font_awesome_flutter: ^10.8.0
  another_carousel_pro: ^1.0.2
  google_maps_flutter: ^2.10.0
  custom_info_window: ^1.0.1
  google_sign_in: ^6.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true
  
  assets:
    - asset/images/
    - asset/images/book_cover.png
    - asset/images/marker.png